/** Arabic display names for common club names (fallback: English). */
export const TEAM_NAME_AR: Record<string, string> = {
  Arsenal: "آرسنال",
  "Aston Villa": "أستون فيلا",
  Bournemouth: "بورنموث",
  Brentford: "برينتفورد",
  Brighton: "برايتون",
  "Brighton and Hove Albion": "برايتون",
  Chelsea: "تشيلسي",
  "Crystal Palace": "كريستال بالاس",
  Everton: "إيفرتون",
  Fulham: "فولهام",
  Ipswich: "إيبسويتش",
  "Ipswich Town": "إيبسويتش",
  Leicester: "ليستر",
  "Leicester City": "ليستر",
  Liverpool: "ليفربول",
  "Manchester City": "مانشستر سيتي",
  "Man City": "مانشستر سيتي",
  "Manchester United": "مانشستر يونايتد",
  "Man United": "مانشستر يونايتد",
  Newcastle: "نيوكاسل",
  "Newcastle United": "نيوكاسل",
  "Nott'm Forest": "نوتينغهام فورست",
  "Nottingham Forest": "نوتينغهام فورست",
  Southampton: "ساوثهامبتون",
  Tottenham: "توتنهام",
  "Tottenham Hotspur": "توتنهام",
  "West Ham": "وست هام",
  "West Ham United": "وست هام",
  Wolves: "وولفرهامبتون",
  "Wolverhampton Wanderers": "وولفرهامبتون",
  "Real Madrid": "ريال مدريد",
  Barcelona: "برشلونة",
  "Atletico Madrid": "أتلتيكو مدريد",
  "Ath Madrid": "أتلتيكو مدريد",
  Sevilla: "إشبيلية",
  Valencia: "فالنسيا",
  Villarreal: "فياريال",
  "Real Sociedad": "ريال سوسيداد",
  Sociedad: "ريال سوسيداد",
  "Athletic Club": "أتلتيك بلباو",
  "Ath Bilbao": "أتلتيك بلباو",
  Betis: "ريال بيتيس",
  "Real Betis": "ريال بيتيس",
  Girona: "جيرونا",
  Osasuna: "أوساسونا",
  Mallorca: "مايوركا",
  Celta: "سيلتا فيغو",
  "Celta Vigo": "سيلتا فيغو",
  Getafe: "خيتافي",
  Alaves: "ألافيس",
  "Rayo Vallecano": "رايو فاليكانو",
  Vallecano: "رايو فاليكانو",
  Espanyol: "إسبانيول",
  "Las Palmas": "لاس بالماس",
  Leganes: "ليغانيس",
  Valladolid: "بلد الوليد",
  Bayern: "بايرن ميونخ",
  "Bayern Munich": "بايرن ميونخ",
  Dortmund: "دورتموند",
  "Borussia Dortmund": "دورتموند",
  Leverkusen: "باير ليفركوزن",
  Leipzig: "لايبزيغ",
  "RB Leipzig": "لايبزيغ",
  Frankfurt: "فرانكفورت",
  "Ein Frankfurt": "فرانكفورت",
  "Eintracht Frankfurt": "فرانكفورت",
  Wolfsburg: "فولفسبورغ",
  Gladbach: "غلادباخ",
  "M'gladbach": "غلادباخ",
  Freiburg: "فرايبورغ",
  Stuttgart: "شتوتغارت",
  Hoffenheim: "هوفنهايم",
  "Werder Bremen": "فيردر بريمن",
  Bremen: "فيردر بريمن",
  Augsburg: "أوغسبورغ",
  "Union Berlin": "يونيون برلين",
  "Mainz 05": "ماينز",
  Mainz: "ماينز",
  "FC Koln": "كولن",
  Koln: "كولن",
  "Heidenheim": "هايدنهايم",
  "St Pauli": "سانت باولي",
  "Holstein Kiel": "هولشتاين كيل",
  Hamburg: "هامبورغ",
  "Hamburger SV": "هامبورغ",
  Bielefeld: "بيليفيلد",
  Bochum: "بوخوم",
  Darmstadt: "دارمشتات",
  "Schalke 04": "شالكه",
  "Greuther Furth": "غرويتر فورت",
  Juventus: "يوفنتوس",
  Inter: "إنتر ميلان",
  Milan: "ميلان",
  Napoli: "نابولي",
  Roma: "روما",
  Lazio: "لاتسيو",
  Atalanta: "أتالانتا",
  Fiorentina: "فيورنتينا",
  Bologna: "بولونيا",
  Torino: "تورينو",
  Genoa: "جنوى",
  Udinese: "أودينيزي",
  Sassuolo: "ساسولو",
  Empoli: "إمبولي",
  Monza: "مونزا",
  Lecce: "ليتشي",
  Verona: "فيرونا",
  Cagliari: "كالياري",
  Parma: "بارما",
  Como: "كومو",
  Venezia: "فينيسيا",
  PSG: "باريس سان جيرمان",
  "Paris SG": "باريس سان جيرمان",
  "Paris Saint Germain": "باريس سان جيرمان",
  Marseille: "مارسيليا",
  Lyon: "ليون",
  Monaco: "موناكو",
  Lille: "ليل",
  Nice: "نيس",
  Rennes: "رين",
  Strasbourg: "ستراسبورغ",
  Lens: "لانس",
  Nantes: "نانت",
  Toulouse: "تولوز",
  Reims: "ريمس",
  Montpellier: "مونبلييه",
  Brest: "بريست",
  Auxerre: "أوكسير",
  Angers: "أنجيه",
  "Le Havre": "لوهافر",
  "St Etienne": "سانت إتيان",
  "Paris FC": "باريس إف سي",
  Lorient: "لوريان",
  Metz: "ميتز",
  Troyes: "تروا",
  Clermont: "كليرمون",
  Ajaccio: "أجاكسيو",
  Bordeaux: "بوردو",
  // Promoted / API leftovers (2026–27)
  "Coventry City FC": "كوفنتري",
  Coventry: "كوفنتري",
  "Hull City AFC": "هل سيتي",
  Hull: "هل سيتي",
  "Málaga CF": "مالقة",
  Malaga: "مالقة",
  "RC Deportivo La Coruña": "ديبورتيفو لا كورونيا",
  Deportivo: "ديبورتيفو لا كورونيا",
  "Real Racing Club de Santander": "راسينغ سانتاندر",
  "Racing Santander": "راسينغ سانتاندر",
  "Le Mans FC": "لو مان",
  "SC Paderborn 07": "بادربورن",
  "SV 07 Elversberg": "إلفرسبرغ",
  Frosinone: "فروزينوني",
  Cremonese: "كريمونيسي",
  Pisa: "بيزا",
  Spezia: "سبيتسيا",
  Salernitana: "ساليرنيتانا",
  Sampdoria: "سامبدوريا",
  Espanol: "إسبانيول",
  Sunderland: "سندرلاند",
  Leeds: "ليدز",
  Elche: "إلتشي",
  Levante: "ليفانتي",
  Oviedo: "أوفييدو",
  // K League 1
  "FC Seoul": "إف سي سيول",
  "Ulsan HD": "أولسان إتش دي",
  "Ulsan HD FC": "أولسان إتش دي",
  "Ulsan Hyundai": "أولسان هيونداي",
  "Jeonbuk Hyundai Motors": "جونبوك هيونداي",
  "Pohang Steelers": "بوهانغ ستيلرز",
  "Gangwon FC": "غانغوون",
  "Gwangju FC": "غوانغجو",
  "Daejeon Hana Citizen": "دايجون هانا",
  "Incheon United": "إنتشون يونايتد",
  "Incheon United FC": "إنتشون يونايتد",
  "Jeju SK": "جيجو إس كيه",
  "Jeju SK FC": "جيجو إس كيه",
  "Jeju United": "جيجو يونايتد",
  "Jeju United FC": "جيجو يونايتد",
  "FC Anyang": "إف سي أنيانغ",
  "Bucheon FC 1995": "بوتشيون 1995",
  "Gimcheon Sangmu": "غيمتشون سانغمو",
  "Gimcheon Sangmu FC": "غيمتشون سانغمو",
  "Sangju Sangmu": "سانغجو سانغمو",
  "Suwon Samsung Bluewings": "سوون سامسونغ",
  "Suwon FC": "سوون إف سي",
  "Daegu FC": "دايغو",
  // Primeira Liga (Portugal)
  Benfica: "بنفيكا",
  Porto: "بورتو",
  "Sporting CP": "سبورتينغ لشبونة",
  Sporting: "سبورتينغ لشبونة",
  "Sporting Lisbon": "سبورتينغ لشبونة",
  Braga: "براغا",
  "Sp Braga": "براغا",
  "Vit Guimaraes": "فيتوريا غيماريش",
  "Vitoria Guimaraes": "فيتوريا غيماريش",
  Boavista: "بوافيستا",
  "Rio Ave": "ريو أفي",
  Famalicao: "فاماليساو",
  Estoril: "إستوريل",
  "Gil Vicente": "جيل فيسينتي",
  Arouca: "أروكا",
  Moreirense: "موريرينسي",
  "Santa Clara": "سانتا كلارا",
  Farense: "فارينسي",
  "Casa Pia": "كاسا بيا",
  Nacional: "ناسيونال ماديرا",
  "Estrela Amadora": "إستريلا أمادورا",
  AVS: "أفاي إف سي",
  // Eredivisie (Netherlands)
  Ajax: "أياكس",
  PSV: "بي إس في آيندهوفن",
  "PSV Eindhoven": "بي إس في آيندهوفن",
  Feyenoord: "فينورد",
  AZ: "إيه زد ألكنار",
  "AZ Alkmaar": "إيه زد ألكنار",
  "FC Twente": "تفينتي",
  Twente: "تفينتي",
  "FC Utrecht": "أوترخت",
  Utrecht: "أوترخت",
  Heerenveen: "هيرنفين",
  Groningen: "غرونينغن",
  Vitesse: "فيتيس أرنهم",
  "Sparta Rotterdam": "سبارتا روتردام",
  "Go Ahead Eagles": "غو أهد إيغلز",
  "NEC Nijmegen": "إن إي سي نيميخن",
  Nijmegen: "إن إي سي نيميخن",
  "PEC Zwolle": "بي إي سي زفوله",
  Zwolle: "بي إي سي زفوله",
  "Fortuna Sittard": "فورتونا سيتارد",
  Heracles: "هيراكليس",
  "RKC Waalwijk": "آر كيه سي فالفايك",
  "Almere City": "ألميري سيتي",
  "NAC Breda": "إن إيه سي بريدا",
  "Willem II": "فيلم 2",
  // Süper Lig (Turkey)
  Galatasaray: "غالاتاسراي",
  Fenerbahce: "فنربخشة",
  Besiktas: "بيشكتاش",
  Trabzonspor: "طرابزون سبور",
  Basaksehir: "باشاك شهير",
  "Istanbul Basaksehir": "باشاك شهير",
  "Adana Demirspor": "أضنة دميرسبور",
  Antalyaspor: "أنطاليا سبور",
  Alanyaspor: "ألانيا سبور",
  Sivasspor: "سيفاسبور",
  Konyaspor: "قونية سبور",
  Kasimpasa: "قاسم باشا",
  Kayserispor: "قايسري سبور",
  Gaziantep: "غازي عنتاب",
  "Gaziantep FK": "غازي عنتاب",
  Rizespor: "ريزي سبور",
  Samsunspor: "سامسون سبور",
  Hatayspor: "هاتاي سبور",
  Goztepe: "غوزتيبي",
  Eyupspor: "أيوب سبور",
  Bodrum: "بودروم إف سي",
  "Seongnam FC": "سونغنام",
};

export function toArabicName(english: string): string {
  if (TEAM_NAME_AR[english]) return TEAM_NAME_AR[english];
  const key = Object.keys(TEAM_NAME_AR).find(
    (k) => k.toLowerCase() === english.toLowerCase(),
  );
  return key ? TEAM_NAME_AR[key] : english;
}
